services: 
  knowledge-demo:
    env_file: 
    - setup.env
    - ./modules/knowledge-demo/config.env
    build: ./modules/knowledge-demo/.
    expose:
    - 7200
    ports: ["7200:7200"]
    entrypoint: 
    - "/entrypoint.sh"
    depends_on: []