x-service-defaults: &service_defaults
  env_file: config.env
  networks: 
  - dockernetwork
  expose: 
  - 5000

services:
  knowledge:
    << : *service_defaults
    build: ./knowledge/.
    expose:
    - 7200
    ports: ["7200:7200"]

  # Johanna + Shihan + Selene + Pei-Yu + Floris
  # - Question Reasoning (rule-based): Floris 
  # - Advice Reasoning: Johanna
  reasoning:
    << : *service_defaults
    build: ./reasoning/.
    volumes:
    - ./reasoning/app:/app
    - ./reasoning/data:/data

  # Cristina + Floris
  response-generator:
    << : *service_defaults
    build: ./response-generator/.
    volumes:
    - ./response-generator/app:/app
  
  # Stergios + Selene/Floris
  text-to-triples:
    << : *service_defaults
    build: ./text-to-triples/.
    volumes:
    - ./text-to-triples/app:/app
  
  # Quirine
  front-end:
    << : *service_defaults
    build: ./front-end/.
    ports: ["8000:8000"]
    volumes:
    - ./front-end/src:/src
    - ./front-end/data:/data
  
  redis:
    << : *service_defaults
    image: redis:latest
    volumes:
      - redisdata:/data

  # Shaad
  logger:
    << : *service_defaults
    build: ./logger/.
    ports: ["8010:5000"]
    volumes:
    - ./logger/app:/app
    - ./logger/logs:/logs
    # Otherwise we get double logging in the console. NOTE: for some reason not working...
    logging:
      driver: none

networks:
  dockernetwork:
    driver: bridge

volumes:
  redisdata: