x-service-defaults: &service_defaults
  env_file: config.env
  networks: dockernetwork
  expose: 
  - 5000

services:
  knowledge:
    << : *service_defaults
    build: ./knowledge/.
    expose:
    - 7200
    ports: ["7200:7200"]
    networks:
    - dockernetwork

  # Johanna + Shihan + Selene + Pei-Yu + Floris
  # - Question Reasoning (rule-based): Floris 
  # - Advice Reasoning: Johanna
  reasoning:
    << : *service_defaults
    build: ./reasoning/.
    networks:
    - dockernetwork
    volumes:
    - ./reasoning/app:/app
    - ./reasoning/data:/data

  # Cristina + Floris
  response-generator:
    << : *service_defaults
    build: ./response-generator/.
    networks:
    - dockernetwork
    volumes:
    - ./response-generator/app:/app
  
  # Stergios + Selene/Floris
  text-to-triples:
    << : *service_defaults
    build: ./text-to-triples/.
    networks:
    - dockernetwork
    volumes:
    - ./text-to-triples/src:/src
  
  # Quirine
  front-end:
    << : *service_defaults
    build: ./front-end/.
    ports: ["8000:8000"]
    networks:
    - dockernetwork
    volumes:
    - ./front-end/src:/src
    - ./front-end/data:/data
  
  # Shaad
  logger:
    << : *service_defaults
    build: ./logger/.
    ports: ["8010:5000"]
    networks:
    - dockernetwork
    volumes:
    - ./logger/app:/app
    - ./logger/logs:/logs

networks:
  dockernetwork:
    driver: bridge